name: 1R2R
channels:
  - conda-forge
  - defaults
dependencies:
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgomp=9.3.0
  - libprotobuf=3.15.8
  - libstdcxx-ng=9.3.0
  - openssl=1.1.1
  - patchelf=0.9
  - pip=20.0.2
  - python=3.7.11
  - typing_extensions=4.1.1
  - wandb=0.12.10
  - yaml=0.2.5
  - pip:
    - absl-py==0.7.0
    - aido-protocols-daffy==6.0.59
    - aiosignal==1.2.0
    - asn1crypto==0.24.0
    - astor==0.7.1
    - atari-py==0.2.9
    - atomicwrites==1.2.1
    - attrs==18.2.0
    - backcall==0.2.0
    - base58==1.0.3
    - beautifulsoup4==4.7.1
    - cachetools==3.0.0
    - carnivalmirror==0.6.2
    - cbor2==5.4.2.post1
    - cffi==1.11.5
    - chardet==3.0.4
    - click==8.0.4
    - cloudpickle==1.2.0
    - colorama==0.3.9
    - coloredlogs==15.0.1
    - coverage==6.3.2
    - cryptography==2.3.1
    - cycler==0.10.0
    - cython==0.29.1
    - d4rl==1.1
    - dask==1.0.0
    - dataclasses-json==0.5.7
    - decorator==4.3.0
    - deepdiff==3.3.0
    - distlib==0.3.4
    - dm-control==0.0.403778684
    - dm-env==1.5
    - dm-tree==0.1.6
    - docutils==0.14
    - dotmap==1.3.8
    - duckietown-serialization-ds1==1.0.20
    - duckietown-world-daffy==6.2.38
    - fasteners==0.17.3
    - filelock==3.6.0
    - flask==2.0.1
    - flatbuffers==1.10
    - freetype-py==2.2.0
    - frozendict==2.3.1
    - frozenlist==1.3.0
    - funcsigs==1.0.2
    - future==0.17.1
    - gast==0.2.0
    - gitdb2==2.0.5
    - gitpython==2.1.11
    - glfw==1.7.0
    - gltflib==1.0.12
    - google-api-python-client==1.7.5
    - google-auth==1.6.1
    - google-auth-httplib2==0.0.3
    - google-pasta==0.2.0
    - gpflow==1.4.1
    - grpcio==1.43.0
    - gtimer==1.0.0b5
    - gym==0.17.3
    - h5py==2.8.0
    - httplib2==0.12.0
    - humanfriendly==10.0
    - idna==2.7
    - imageio==2.4.1
    - importlib-metadata==4.11.1
    - importlib-resources==5.6.0
    - ipython==7.32.0
    - itsdangerous==2.1.0
    - jedi==0.18.1
    - jinja2==3.0.3
    - jmespath==0.9.3
    - jpeg4py==0.1.4
    - jsonpickle==2.1.0
    - jsonschema==4.4.0
    - keras-applications==1.0.6
    - keras-preprocessing==1.0.5
    - kiwisolver==1.0.1
    - labmaze==1.0.5
    - lockfile==0.12.2
    - lxml==4.8.0
    - lz4==4.0.0
    - markdown==3.0.1
    - markupsafe==2.1.0
    - marshmallow==3.15.0
    - marshmallow-enum==1.5.1
    - matplotlib==3.0.2
    - matplotlib-inline==0.1.3
    - more-itertools==4.3.0
    - morphys==1.0
    - msgpack==1.0.3
    - mujoco-py==2.1.2.14
    - multipledispatch==0.6.0
    - mypy-extensions==0.4.3
    - networkx==2.2
    - nose==1.3.7
    - numpy==1.16.0
    - opencv-python==4.5.5.64
    - opencv-python-headless==4.5.5.62
    - oyaml==1.0
    - packaging==21.3
    - pandas==0.23.4
    - parso==0.8.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==6.2.0
    - platformdirs==2.5.2
    - plotly==5.1.0
    - pluggy==0.8.0
    - prompt-toolkit==3.0.29
    - protobuf==3.19.4
    - psutil==5.4.8
    - ptyprocess==0.7.0
    - py==1.7.0
    - py-cid==0.3.0
    - py-multibase==1.0.3
    - py-multicodec==0.2.1
    - py-spy==0.3.11
    - pyasn1==0.4.4
    - pyasn1-modules==0.2.2
    - pybase64==1.2.1
    - pybullet==3.2.1
    - pycontracts3==3.0.2
    - pycparser==2.19
    - pygame==1.9.4
    - pygeometry-z6==2.1.4
    - pyglet==1.4.10
    - pygments==2.11.2
    - pyopengl==3.1.0
    - pyopenssl==18.0.0
    - pyparsing==2.3.0
    - pyqt5==5.15.6
    - pyqt5-qt5==5.15.2
    - pyqt5-sip==12.9.1
    - pyrsistent==0.18.1
    - pysocks==1.6.8
    - pytest==4.0.1
    - python-baseconv==1.2.2
    - python-dateutil==2.7.5
    - pytz==2018.7
    - pywavelets==1.0.1
    - pyyaml==4.2b4
    - pyzmq==22.3.0
    - redis==3.0.1
    - requests==2.28.1
    - rsa==3.4.2
    - s3transfer==0.1.13
    - scikit-image==0.14.2
    - scikit-learn==0.20.1
    - scipy==1.1.0
    - git+https://github.com/hartikainen/serializable.git@76516385a3a716ed4a2a9ad877e2d5cbcf18d4e6
    - setproctitle==1.1.10
    - smmap2==2.0.5
    - soupsieve==2.3.2
    - svgwrite==1.4.2
    - tenacity==8.0.1
    - tensorboard==1.14.0
    - tensorboardx==1.8
    - tensorflow-estimator==1.14.0
    - tensorflow-gpu==1.14.0
    - tensorflow-probability==0.7.0
    - termcolor==1.1.0
    - toolz==0.9.0
    - tqdm==4.32.1
    - traitlets==5.1.1
    - trimesh==3.10.7
    - typing==3.7.4.3
    - typing-inspect==0.7.1
    - uritemplate==3.0.0
    - urllib3==1.26.11
    - validate-email==1.3
    - varint==1.0.2
    - virtualenv==20.14.1
    - wcwidth==0.2.5
    - webcolors==1.11.1
    - werkzeug==2.0.3
    - wrapt==1.13.3
    - xtermcolor==1.3
    - zipp==3.7.0
    - zuper-commons-z6==6.2.4
    - zuper-ipce-z6==6.1.2
    - zuper-nodes-z6==6.2.13
    - zuper-typing-z6==6.2.3
